/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';

import '@ionic/core';
import 'ionicons';
import {
  EventEmitter,
} from '@stencil/core';
import {
  StyleEventDetail,
} from '@ionic/core';


export namespace Components {

  interface IonImagePicker {
    /**
    * If `true`, the user cannot interact with the datetime.
    */
    'disabled': boolean;
    /**
    * 最多显示多少张图片
    */
    'max': number;
    /**
    * Opens the datetime overlay.
    */
    'open': () => Promise<void>;
    /**
    * If `true`, the datetime appears normal but is not interactive.
    */
    'readonly': boolean;
  }
  interface IonImagePickerAttributes extends StencilHTMLAttributes {
    /**
    * If `true`, the user cannot interact with the datetime.
    */
    'disabled'?: boolean;
    /**
    * 最多显示多少张图片
    */
    'max'?: number;
    /**
    * Emitted when the value (selected date) has changed.
    */
    'onIonChange'?: (event: CustomEvent<void>) => void;
    /**
    * If `true`, the datetime appears normal but is not interactive.
    */
    'readonly'?: boolean;
  }
}

declare global {
  interface StencilElementInterfaces {
    'IonImagePicker': Components.IonImagePicker;
  }

  interface StencilIntrinsicElements {
    'ion-image-picker': Components.IonImagePickerAttributes;
  }


  interface HTMLIonImagePickerElement extends Components.IonImagePicker, HTMLStencilElement {}
  var HTMLIonImagePickerElement: {
    prototype: HTMLIonImagePickerElement;
    new (): HTMLIonImagePickerElement;
  };

  interface HTMLElementTagNameMap {
    'ion-image-picker': HTMLIonImagePickerElement
  }

  interface ElementTagNameMap {
    'ion-image-picker': HTMLIonImagePickerElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
